version: 0.0
os: linux
files:
  - source: /
    destination: /app/YouTube-Client
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 600
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60