version: 0.0
os: linux
files:
  - source: /
    destination: /app
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ec2-user
