version: 0.0
os: linux
files:
  - source: /
    destination: /app/YouTube-Client
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: post_install.sh
      timeout: 600
  ApplicationStart:
    - location: run.sh
      timeout: 120
  ApplicationStop:
    - location: stop.sh
      timeout: 120
  ValidateService:
    - location: validate.sh
      timeout: 60